apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "desafio-jacks.fullname" . }}-configmap
  labels:
    app: {{ include "desafio-jacks.name" . }}
    desafio: jackexperts
data:
  index.html: |
    {{ .Values.configMap.htmlContent | indent 4 }}