apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "desafio-jacks.fullname" . }}-configmap
  labels:
    app: {{ include "desafio-jacks.name" . }}
    desafio: jackexperts
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Página Customizável via Helm</title>
    </head>
    <body>
        <h1>Bem-vindo ao Desafio Jacks</h1>
        <p>Esta página foi customizada via ConfigMap e Helm.</p>
    </body>
    </html>
