apiVersion: v1
kind: Service
metadata:
  name: {{ include "desafio-jacks.fullname" . }}
  labels:
    app: {{ include "desafio-jacks.name" . }}
    desafio: jackexperts
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "desafio-jacks.name" . }}
